### ISSUE TITLE
Using via cdn

### ISSUE THREAD

**Issue by WpSlt** [teamseodo/vue3-tree#100]
Using cdn I got:
[Vue warn]: Component is missing template or render function. 
  at <Tree nodes= (2) [{…}, {…}]0: {id: 1, label: 'Animal', nodes: Array(2)}1: {id: 6, label: 'People'}length: 2[[Prototype]]: Array(0) onUpdate:nodes=fn<onUpdate:nodes> > 

with following code:

    <div id="trest">
		<Tree v-model:nodes="data" />
    </div>

const test = Vue.createApp({
	  components: {
    Tree,
  },
setup() {
    const data = Vue.ref([
      {
        id: 1,
        label: 'Animal',
        nodes: [
          {
            id: 2,
            label: 'Dog',
          },
          {
            id: 3,
            label: 'Cat',
            nodes: [
              {
                id: 4,
                label: 'Egyptian Mau Cat',
              },
              {
                id: 5,
                label: 'Japanese Bobtail Cat',
              },
            ],
          },
        ],
      },
      {
        id: 6,
        label: 'People',
      },
    ]);

    return {
      data,
    };
  }
});
test.component("Tree", Tree)
const testEl = test.mount('#test')

**Comment by kadiryazici** [comment]
Hi, I think this is because we didn't specify a build option for `unpkg` or `jsdelivr`. With this PR I hope it'll be fixed https://github.com/teamseodo/vue3-tree/pull/101
