### ISSUE TITLE
Installation Bug

### ISSUE THREAD

**Issue by ishaiavrahami** [teamseodo/vue3-tree#41]
3:29:36 PM [vite] Internal server error: Failed to resolve entry for package "vue3-tree". The package may have incorrect main/module/exports specified in its package.json.

**Comment by alpercun** [comment]
> 3:29:36 PM [vite] Internal server error: Failed to resolve entry for package "vue3-tree". The package may have incorrect main/module/exports specified in its package.json.

released v0.1.3 🎉
