### ISSUE TITLE
Support empty nodes array

### ISSUE THREAD

**Issue by matschik** [teamseodo/vue3-tree#89]
Hello ! Thanks a lot for your open-source library 🙏 

**Problem**
I encounter a problem when nodes array are empty.
When I check a node, there is a bug because it checks everything.
https://codesandbox.io/s/agitated-snyder-fvvqh?file=/src/App.vue

**Solution**
Once I delete all empty `nodes` array. The problem was solved.

**Proposal**
Is it possible to support empty `nodes` array to behave the same way as `nodes` is missing ?
The other advantage is to remove the right arrow when `nodes` array is empty too as seen in the CodeSandbox link above.

**Comment by aykutkardas** [comment]
You are right, thanks for your feedback. We will fix this as soon as possible.

**Comment by aykutkardas** [comment]
You can use the `v0.10.0` version. @matschik
