### ISSUE TITLE
How do I handle initial checked nodes ?

### ISSUE THREAD

**Issue by matschik** [teamseodo/vue3-tree#91]
I don't see any prop to handle initial checked nodes.
I think it's a common feature for a tree component.
Am I missing something ?

**Comment by aykutkardas** [comment]
Actually this project has not been released yet and is still in development. But we forgot to declare it in the README.

However, I will quickly integrate this feature you reminded me of. Thanks for your feedback.

**Comment by aykutkardas** [comment]
You can use the `v0.10.0` version. @matschik 

Check docs: https://teamseodo.github.io/vue3-tree/guide/props.html#nodes

**Comment by matschik** [comment]
It's working like a charm ! 
Thank you so much 🙏 
Amazing reactivity 🔥
