### ISSUE TITLE
Support for onClickNode?

### ISSUE THREAD

**Issue by ngoloc10796** [teamseodo/vue3-tree#96]
I can't handle when click node. Can you help me?
Thank you!

**Comment by aykutkardas** [comment]
Hi @ngoloc10796 👋🏻 

This support is not yet available. But we will add that shortly.

**Comment by aykutkardas** [comment]
Hi again @ngoloc10796 👋🏻 

First upgrade the `vue3-tree` package to version `0.11.0`.

Then you can use it like below.

```vue
  <Tree
    :nodes="data"
    :use-checkbox="true"
    :use-icon="true"
    @nodeClick="onNodeClick"
  />
```

```js
const onNodeClick = (node) => {
  console.log(node);
};
```

**Comment by ngoloc10796** [comment]
thank you!
